services:
  postgres:
    container_name: postgres
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=spring_modulith'
      - 'POSTGRES_PASSWORD=modulith'
      - 'POSTGRES_USER=modulith'
    ports:
      - '5432:5432'

    volumes:
      - /Users/alinabohoslavets/IdeaProjects/SpringModulithCourse/tmp/modulith:/var/lib/postgresql/data

volumes:
  postgres: