spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

  modulith:
    events:
      republish-outstanding-events-on-restart: false

delete:
  event:
    duration: 5000

#logging:
#  level:
#    org.springframework.modulith: DEBUG
#    org.springframework.web: DEBUG