spring:
  datasource:
    username: modulith
    password: modulith
    url: jdbc:postgresql://postgres:5432/spring_modulith
#    url: jdbc:postgresql://localhost:5432/spring_modulith # run not in docker container

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

  modulith:
    events:
      republish-outstanding-events-on-restart: false

delete:
  event:
    duration: 5000

#logging:
#  level:
#    org.springframework.modulith: DEBUG
#    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

#server:
#  port: 8081
